### ISSUE TITLE
Window outline at corners

### ISSUE THREAD

**Issue by RafeeDaBoy** [matinlotfali/KDE-Rounded-Corners#36] opened 2022-06-01 07:15 UTC
There's a gray window border at the corners
![image](https://user-images.githubusercontent.com/69535896/171348815-c52d1e09-e549-4196-b411-4abd39c85694.png)

**Comment by matinlotfali** [comment] 2022-06-01 07:51
This is a duplicate of issue #2

**Closed** 2022-06-01 07:51 UTC
Labels: duplicate
