### ISSUE TITLE
outline disappear and reappear repeatedly when dragging window under fractional scale

### ISSUE THREAD

**Issue by mill413** [matinlotfali/KDE-Rounded-Corners#181] opened 2024-03-14 04:16 UTC
I am using a monitor with 150% scaling, and when I drag a window on it, the outline will disappear and reappear repeatedly.

The outline thickness in video is 5.

https://github.com/matinlotfali/KDE-Rounded-Corners/assets/49865696/1e41049c-c6e4-4878-a917-7e825577538b

I am using archlinux+plasma6.0.2

**Comment by matinlotfali** [comment] 2024-03-30 19:21
Thanks for the video. Is it on Wayland? or X11?

**Comment by mill413** [comment] 2024-03-31 00:42
> Thanks for the video. Is it on Wayland? or X11?

It's Wayland. And I update to plasma 6.0.3, it still happen.

**Comment by mill413** [comment] 2024-05-07 01:51
> I still can't reproduce this. Is the issue still present?

Yes, it's still on my computer. And I found that applications based on qt, such as telegram, konsole, dolphin and obs studio, has this weird behavior, maybe it's a qt's bug.

**Comment by taj-ny** [comment] 2024-05-11 13:01
I'm also experiencing this issue on v0.6.5 and Plasma v6.0.4. Whether the outline is drawn seems to depend on the window's Y position (although not always). Resizing a window by its top edge is probably the easiest way to reproduce this. Disabling the window frame with a rule may help as well.

**Comment by matinlotfali** [comment] 2024-05-18 21:29
I tried very hard to reproduce it but still no luck. It might be a graphics driver issue. Can you confirm that the issue exists on other distros or other graphics drivers?

**Comment by taj-ny** [comment] 2024-05-19 04:35
Looks like this issue was fixed by aa3ba874f5769a3b36c28901488643be3eb615d0.

**Comment by mill413** [comment] 2024-05-19 06:43
It has been fixed after upgrading. Thanks for your work!

**Closed** 2024-05-19 06:55 UTC
Labels: cant-reproduce

**Comment by matinlotfali** [comment] 2024-05-19 19:50
That is great news. I made some fixes unrelated to disappearing and reappearing outlines but apparently, it fixed other stuff too.
