### ISSUE TITLE
Rounded corners at fullscreen windows

### ISSUE THREAD

**Issue by karolproksa** [matinlotfali/KDE-Rounded-Corners#12] opened 2021-11-07 17:15 UTC
As mentioned in the title. When for example playing fullscreen videos we can see the rounded corners.

**Comment by matinlotfali** [comment] 2021-11-20 03:36
I need more information. What app do you use to see fullscreen videos? A screenshot would also be nice.

**Comment by lk-vila** [comment] 2021-11-21 17:08
It happens to me also. I'll use vlc as an example, this is a screenshot that i just took:
![Screenshot_20211121_140500](https://user-images.githubusercontent.com/53627437/142771920-28bdf3a3-b470-4f67-a817-55a3113db8c4.png)

**Comment by matinlotfali** [comment] 2021-11-21 22:05
Is the issue a duplicate of issue #3 ?

**Comment by MyFilippo94** [comment] 2021-12-23 19:24
Can confirm, happened with Mozilla Firefox and MPV Player too.
This is Firefox, on Youtube
![image](https://user-images.githubusercontent.com/33789014/147283945-2bf1e995-17a8-46aa-93cc-0f2208f7c60c.png)

**Closed** 2022-02-27 04:25 UTC
Labels: bug, question
