### ISSUE TITLE
Borders are not appearing on maximized if i uncheck "maximized windows" on exclude

### ISSUE THREAD

**Issue by hrqmonteiro** [matinlotfali/KDE-Rounded-Corners#156] opened 2024-01-28 04:44 UTC
https://github.com/matinlotfali/KDE-Rounded-Corners/assets/17055027/dc27fa27-306e-4027-8a09-fd35cc8a1330

It should keep the borders on maximized windows if i uncheck it.

**Comment by matinlotfali** [comment] 2024-01-28 20:18
Can you try #105 and see if the issue is fixed in it?

**Comment by matinlotfali** [comment] 2024-02-02 01:30
Merged #105. Please reopen the issue if the issue is not resolved.

**Closed by matinlotfali** 2024-02-02 01:30 UTC
