### ISSUE TITLE
Korners visible on Konsole

### ISSUE THREAD

**Issue by debnath-d** [matinlotfali/KDE-Rounded-Corners#163] opened 2024-02-04 04:25 UTC
Other windows are fine. See screenshot:

![Screenshot_2024_02_04_09_53_34](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/16205994/76f38f4e-ec34-4429-b5ed-aa7e66b5e027)

**Comment by matinlotfali** [comment] 2024-02-04 22:00
Closing as it is a duplicate of #100

**Closed by matinlotfali** 2024-02-04 22:00 UTC
