### ISSUE TITLE
[feature request] allow disabling roundness on maximize but not tile

### ISSUE THREAD

**Issue by queenbiscuit311** [matinlotfali/KDE-Rounded-Corners#205] opened 2024-04-06 22:59 UTC
Current behavior makes it so that when the window is tiled rounding is disabled. Depending on your theme though this may not look the best along with normal rounded windows. For example on my theme and while using lightlyshaders blur, having windows not rounded when tiled looks a bit weird. Would it be possible to have a setting to only disable roundness when maximized? I personally don't mind if tiled windows are rounded as long as maximized windows aren't.

I don't mean to sound like im pressuring or anything, i just think this would improve the effect by a bit for some themes.

**Comment by 4nyNoob** [comment] 2024-04-10 13:13
this is a duplicate of #190

**Closed** 2024-04-17 23:19 UTC
Labels: enhancement
