### ISSUE TITLE
Strange white border on right side of the windows

### ISSUE THREAD

**Issue by hrqmonteiro** [matinlotfali/KDE-Rounded-Corners#189] opened 2024-03-20 20:43 UTC
![image](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/17055027/d6e71f28-aa1f-437d-9e54-938c2085f2d4)
![image](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/17055027/cb9ceab5-c71a-47da-a140-90aae93bd3e6)
![image](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/17055027/ae7202f7-5dc1-4df1-a4a0-0421cc9231f9)

**Comment by hrqmonteiro** [comment] 2024-03-20 20:46
On Spotify is even more apparent in the screenshot:

![image](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/17055027/a4faff42-fd68-43cb-89e9-3493b1f48db9)
![Screenshot_20240320_174628](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/17055027/170efc01-af40-4761-9e88-d0130cbb06f0)

**Comment by Yokox1** [comment] 2024-03-21 15:26
I can confirm that this also happens to me on Plasma 6:
![image](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/70451320/b12e213c-5d3d-4de7-9f8e-43399e6d000e)
![image](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/70451320/733f5bf6-9942-4ffa-8fd6-71aaadceb81c)

**Comment by stankovictab** [comment] 2024-03-24 00:50
Same here, freshly compiled

**Comment by GloriousEggroll** [comment] 2024-03-25 19:52
This is a duplicate of https://github.com/matinlotfali/KDE-Rounded-Corners/issues/180

Read:
https://github.com/matinlotfali/KDE-Rounded-Corners/pull/187/files

**Closed** 2024-03-26 00:17 UTC
