### ISSUE TITLE
General oddities observed in the settings app

### ISSUE THREAD

**Issue by RedBearAK** [matinlotfali/KDE-Rounded-Corners#143] opened 2024-01-20 05:22 UTC
@matinlotfali 

These things are probably not particularly important. 

When I look at the Desktop Effects list, the check box next to your ShapeCorners (shouldn't you be renaming the effect since it's a fork of something by that name?) contains three dots, vertically centered. This also appears on Blur and "Background Contrast", but "Screen Edge" has a check mark. Without context it is difficult to understand what the three dots indicates. In other circumstances I would assume that it indicates that something is only partially enabled, like a header of a sub-list where only some of the items inside are selected. 

In this case I can't even guess why there isn't a check mark rather than the three dots. It's a failure of the KDE settings UI to explain what this means, but it's curious that your new effect gets the three dots, and makes me wonder why. 

When I change the shadow color and click "Apply" it doesn't immediately apply the new color until I move over to a new window where something gets highlighted by hovering, or switch to a different window and back. If it's just the hovering over some items like the list of desktop effects, only a portion of the focused window will change to the new color. This gets fixed when doing a full window focus switch. 

Changing only the "Initial Transparency" settings for active or inactive shadows does not seem to activate the the "Apply" button (it stays dead as if nothing was changed), and doesn't seem to get saved if I just hit "OK" without flipping some other setting in a way that activates the "Apply" button. As if the dialog is not noticing the change of only the transparency settings. However the new transparency setting does get saved if I tweak something else that causes the "Apply" button to wake up, and then hit either "Apply" or "OK".

**Comment by matinlotfali** [comment] 2024-01-20 05:33
All 3 items you mentioned are all valid.

The config name and its checkbox are leftovers from the fork that I never changed.

The new colors are not applying correctly on the new Wayland. It might be a bug on the Plasma side. I need to dig more into it.

The transparency widget is definitely from my end. I need to inform the dialog about this change. This one is the easiest to fix compared to the rest.

**Comment by matinlotfali** [comment] 2024-05-06 05:13
I think the issue is finally resolved with #216, #148, and #147

**Closed by matinlotfali** 2024-05-06 05:13 UTC
Labels: bug
