### ISSUE TITLE
Round but also sharp

### ISSUE THREAD

**Issue by reunitereclaim** [matinlotfali/KDE-Rounded-Corners#20] opened 2022-02-03 03:48 UTC
Hello!
I installed as per instructions.
Corners are rounded
-but behind the corners there is a white square filling in the cut off corner.
This mostly seems to appear when the windows are overlapping but can be seen otherwise with some windows.

Operating System: Kubuntu 21.10
KDE Plasma Version: 5.23.5
KDE Frameworks Version: 5.90.0
Qt Version: 5.15.2
Kernel Version: 5.13.0-28-generic (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-7820HQ CPU @ 2.90GHz
Memory: 31.2 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 630

**Comment by RomanKode** [comment] 2022-02-10 22:18
You have 2 choices, either turn off your decorations shadows or lower it to the lowest size and shadow strength.

**Comment by matinlotfali** [comment] 2022-02-27 00:02
Is it a duplicate of the issue #2?

**Closed** 2022-04-16 16:49 UTC
Labels: duplicate
