### ISSUE TITLE
How to prevent round corners from appearning on extensions, like KLaunch

### ISSUE THREAD

**Issue by hrqmonteiro** [matinlotfali/KDE-Rounded-Corners#155] opened 2024-01-27 21:42 UTC
![image](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/17055027/62e19fb6-e116-428f-af06-8f27c9a97321)

This is [KLaunch](https://store.kde.org/p/1815117), how can i prevent the borders from appearing on it? I can't select it as a window to exclude:

![Screenshot_20240127_184211](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/17055027/c9fd3b6a-5643-4d5c-b1b6-5f076707ea5e)

**Comment by matinlotfali** [comment] 2024-01-28 20:39
Can you test it with #105 and see if it get's resolved?

**Comment by matinlotfali** [comment] 2024-02-02 01:31
Merged #105. Please reopen the issue if the issue is not resolved.

**Closed by matinlotfali** 2024-02-02 01:31 UTC
