### ISSUE TITLE
Install on immutable systems

### ISSUE THREAD

**Issue by Reidond** [matinlotfali/KDE-Rounded-Corners#62] opened 2022-09-19 16:48 UTC
Hi, is it possible to install this for OS like Silverblue?

I tried to change `CMAKE_INSTALL_PREFIX` and `DESTDIR` to `$HOME/.local/share` but not luck, it's not showing in the list

**Comment by matinlotfali** [comment] 2022-09-20 17:07
I have never tried it on Silverblue. I can try it on a virtual machine and try.

**Comment by matinlotfali** [comment] 2022-09-23 00:00
I was able to install the effect on Fedora Kinoite using:
    sudo ostree admin unlock
But it will get removed after a reboot. I don't know how to make it permanent yet.

**Comment by matinlotfali** [comment] 2022-09-23 00:03
I think the issue is not with the effect but more like learning how to edit the root partition in Silverblue. I am closing this issue. If you need to install the effect as a regular user instead of root, you need to open another issue unrelated to Silverblue.

**Closed by matinlotfali** 2022-09-23 00:03 UTC
